'use client';
import { useState } from 'react';
import { usePathname } from 'next/navigation';
import Link from 'next/link';
import { LayoutDashboard, FileText, MessageCircle, Siren, Stethoscope, Menu, X, LogOut, ChevronLeft, ChevronRight } from 'lucide-react';
import { motion } from 'framer-motion';
import { useAuth } from '../lib/auth-context';
import { ThemeLanguage } from './ThemeLanguage';
import { FloatingSOS } from './FloatingSOS';
import { t } from '../lib/i18n';
const items=[['/','dashboard',LayoutDashboard],['/records','records',FileText],['/chat','chat',MessageCircle],['/emergency','emergency',Siren],['/doctor-view','doctor',Stethoscope]] as const;
export function AppShell({children}:{children:React.ReactNode}){const {lang,profile,signOut,loading}=useAuth();const path=usePathname(); const [collapsed,setCollapsed]=useState(false);const [drawer,setDrawer]=useState(false);const title=items.find(([href])=>href===path)?.[1]||'dashboard'; if(loading)return <div className="min-h-screen p-8" style={{background:'var(--bg)'}}/>; return <div className="min-h-screen" style={{background:'var(--bg)'}}>
 <motion.aside animate={{width:collapsed?'72px':'260px'}} className="hidden md:flex fixed inset-y-0 left-0 z-40 flex-col border-r p-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}>
  <div className="flex items-center justify-between mb-8"><Link href="/" className="flex items-center gap-3 font-black text-lg" style={{color:'var(--brand)'}}><span className="h-10 w-10 rounded-2xl flex items-center justify-center text-white" style={{background:'var(--brand)'}}>T</span>{!collapsed&&<span>Tholan</span>}</Link>{!collapsed&&<button onClick={()=>setCollapsed(true)} className="p-2 rounded-lg" aria-label="Collapse sidebar"><ChevronLeft size={18}/></button>}</div>
  {collapsed&&<button onClick={()=>setCollapsed(false)} className="mx-auto mb-4 p-2 rounded-lg" aria-label="Expand sidebar"><ChevronRight size={18}/></button>}
  <nav className="space-y-2">{items.map(([href,key,Icon])=>{const active=path===href;const urgent=key==='emergency';return <Link key={href} href={href} onClick={()=>setDrawer(false)} className="flex items-center gap-3 rounded-xl px-3 py-3 font-semibold" style={{background:active?'var(--surface-strong)':'transparent',color:urgent&&active?'var(--danger)':'var(--text)'}}><Icon size={19}/>{!collapsed&&<span>{t(lang,key as any)}</span>}</Link>})}</nav>
  <div className="mt-auto"><div className="border-t pt-4 mb-4" style={{borderColor:'var(--border)'}}>{!collapsed&&<ThemeLanguage hideLanguage={path==='/doctor-view'}/>}</div><button onClick={signOut} className="w-full flex items-center gap-3 px-3 py-3 rounded-xl font-semibold" style={{color:'var(--text)'}}><LogOut size={19}/>{!collapsed&&'Logout'}</button></div>
 </motion.aside>
 <div className="md:hidden"><div className="fixed top-0 inset-x-0 z-30 h-16 border-b flex items-center px-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}><button onClick={()=>setDrawer(true)} aria-label="Open navigation" className="p-2"><Menu/></button><div className="font-black ml-2" style={{color:'var(--brand)'}}>Tholan</div></div>{drawer&&<div className="fixed inset-0 z-[60] bg-black/40" onClick={()=>setDrawer(false)}><div className="h-full w-[290px] p-5 border-r" style={{background:'var(--surface)',borderColor:'var(--border)'}} onClick={e=>e.stopPropagation()}><div className="flex justify-between mb-8"><span className="font-black" style={{color:'var(--brand)'}}>Tholan</span><button onClick={()=>setDrawer(false)}><X/></button></div>{items.map(([href,key,Icon])=><Link key={href} href={href} onClick={()=>setDrawer(false)} className="flex gap-3 py-3 font-semibold"><Icon size={19}/>{key==='doctor'?'Doctor View':t(lang,key as any)}</Link>)}<div className="border-t mt-4 pt-4"><ThemeLanguage hideLanguage={path==='/doctor-view'}/><button onClick={signOut} className="mt-4 flex gap-3"><LogOut size={19}/>Logout</button></div></div></div>}</div>
 <main className={`${collapsed?'md:ml-[72px]':'md:ml-[260px]'} min-h-screen transition-all`}><div className="hidden md:flex h-16 items-center justify-between border-b px-8 sticky top-0 z-20" style={{background:'color-mix(in srgb, var(--bg) 92%, transparent)',borderColor:'var(--border)',backdropFilter:'blur(10px)'}}><div><div className="text-xs" style={{color:'var(--muted)'}}>Tholan / {profile?.name||'Health'}</div><div className="font-bold">{t(lang,title as any)}</div></div><div className="text-sm" style={{color:'var(--muted)'}}>{profile?.name||''}</div></div><div className="md:hidden h-16"/><motion.div initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} transition={{duration:.2}} className="page-enter p-5 md:p-8 pb-28">{children}</motion.div></main><FloatingSOS/>
 </div>}
