'use client';
import { useEffect, useState } from 'react';
import { createSupabaseBrowser } from '../../lib/supabase-browser';
import { useAuth } from '../../lib/auth-context';
import { AppShell } from '../../components/AppShell';
import { PageHeader } from '../../components/PageHeader';
import type { Condition, Medication, Hospital } from '../../lib/types';
import { toast } from 'sonner';
export default function DoctorView(){const {user,profile}=useAuth();const [data,setData]=useState<{c:Condition[];m:Medication[];h?:Hospital}|null>(null);useEffect(()=>{if(!user)return;const s=createSupabaseBrowser();Promise.all([s.from('conditions').select('*').order('created_at',{ascending:false}),s.from('medications').select('*').order('created_at',{ascending:false}),s.from('hospitals').select('*').eq('is_primary',true).limit(1)]).then(([c,m,h])=>{const er=c.error||m.error||h.error;if(er){toast.error('Could not load doctor view.');return;}setData({c:(c.data||[]) as Condition[],m:(m.data||[]) as Medication[],h:(h.data||[])[0] as Hospital|undefined});});},[user]);return <AppShell><PageHeader title="🩺 Doctor View" subtitle="English-only, read-only summary of the authenticated user's stored health information."/><div className="max-w-5xl space-y-5"><section className="rounded-3xl p-6 border" style={{borderColor:'var(--border)',background:'color-mix(in srgb,var(--navy) 6%,var(--surface))'}}><h2 className="text-2xl font-black">Patient identity</h2><div className="grid sm:grid-cols-2 gap-5 mt-5 text-lg"><div><div className="text-sm font-bold" style={{color:'var(--muted)'}}>Name</div><div className="font-black mt-1">{profile?.name||'Not recorded'}</div></div><div><div className="text-sm font-bold" style={{color:'var(--muted)'}}>Age</div><div className="font-black mt-1">{profile?.age??'Not recorded'}</div></div><div><div className="text-sm font-bold" style={{color:'var(--muted)'}}>Allergies</div><div className="font-black mt-1">Not recorded</div></div><div><div className="text-sm font-bold" style={{color:'var(--muted)'}}>Last updated</div><div className="font-black mt-1">{new Date().toLocaleString('en-IN')}</div></div></div></section><section className="grid lg:grid-cols-2 gap-5"><Block title="Conditions">{data?.c.length?data.c.map(x=><div key={x.id} className="p-4 rounded-xl border" style={{borderColor:'var(--border)'}}><div className="font-black">{x.name}</div>{x.since&&<div className="text-sm">Since: {x.since}</div>}{x.notes&&<div className="text-sm">{x.notes}</div>}</div>):<div className="font-semibold">Not recorded</div>}</Block><Block title="Current medications">{data?.m.length?data.m.map(x=><div key={x.id} className="p-4 rounded-xl border" style={{borderColor:'var(--border)'}}><div className="font-black">{x.name}</div><div className="text-sm">Dosage: {x.dosage||'Not recorded'}</div></div>):<div className="font-semibold">Not recorded</div>}</Block></section><Block title="Primary hospital">{data?.h?<div className="text-lg"><div className="font-black">{data.h.name}</div><div>{data.h.phone_number}</div><div className="text-sm mt-1">Scheme: {data.h.scheme||'None'}</div></div>:<div className="font-semibold">Not recorded</div>}</Block></div></AppShell>}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl p-6 border" style={{borderColor:'var(--border)',background:'var(--surface)'}}><h2 className="text-xl font-black mb-4">{title}</h2><div className="space-y-3">{children}</div></section>}
